# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The personal website of Sven Lieber.'
    twitter: 'SvenLieber'
  analytics:
    google_analytics: 'G-WR7S5DYKLQ'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© 2017-{year} Sven Lieber. This work is licensed under {license} except where otherwise noted.'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04 MST'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/SvenLieber/website'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: 'svenlieber'
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: false

metadata:
  givenName: Sven
  familyName: Lieber
  name: Sven Lieber
  sameas:
    - icon: twitter
      icon_pack: fab
      link: https://twitter.com/SvenLieber
    - icon: linkedin
      icon_pack: fab
      link: https://be.linkedin.com/in/sven-lieber-1b2b70131
    - icon: barcode
      icon_pack: fa
      link: https://www.wikidata.org/entity/Q59469449
    - icon: graduation-cap # Alternatively, use `google-scholar` icon from `ai` icon pack
      icon_pack: fas
      link: https://scholar.google.be/citations?user=-_GsmQgAAAAJ&hl=en
    - icon: github
      icon_pack: fab
      link: https://github.com/SvenLieber
    - icon: orcid
      icon_pack: ai
      link: https://orcid.org/0000-0002-7304-3787
    - icon: dplp
      icon_pack: ai
      link: https://dblp.org/pid/216/2489
    - icon: figshare
      icon_pack: ai
      link: https://figshare.com/authors/wd/10009451
    - icon: zotero
      icon_pack: ai
      link: https://zotero.org/slieber
    - icon: acm-dl
      icon_pack: ai
      link: https://dl.acm.org/profile/99659241698



